server.port=${SPRING_APP_PORT}
server.servlet.context-path=/store/api

# Uso de variables de entorno con valores por defecto opcionales
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
# Recomendado para asegurar que las tablas se creen/actualicen
spring.jpa.hibernate.ddl-auto=update